// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rpc/user/service.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	rpc/user/service.proto

It has these top-level messages:
	CreateReq
	Resp
	IDReq
	ListResp
	ListReq
	UpdateReq
	MessageResp
*/
package user

import regexp "regexp"
import fmt "fmt"
import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _regex_CreateReq_Username = regexp.MustCompile(`^[A-Za-z0-9]+(?:[ _-][A-Za-z0-9]{2,15})*$`)
var _regex_CreateReq_Email = regexp.MustCompile(`^[a-z0-9._\-]+@[a-z0-9.\-]+\.[a-z]{2,4}$`)

func (this *CreateReq) Validate() error {
	if !_regex_CreateReq_Username.MatchString(this.Username) {
		return go_proto_validators.FieldError("Username", fmt.Errorf(`Invalid username format`))
	}
	if !_regex_CreateReq_Email.MatchString(this.Email) {
		return go_proto_validators.FieldError("Email", fmt.Errorf(`Invalid email address`))
	}
	if !(len(this.FirstName) > 2) {
		return go_proto_validators.FieldError("FirstName", fmt.Errorf(`value '%v' must length be greater than '2'`, this.FirstName))
	}
	if !(len(this.FirstName) < 24) {
		return go_proto_validators.FieldError("FirstName", fmt.Errorf(`value '%v' must length be less than '24'`, this.FirstName))
	}
	if !(len(this.LastName) > 2) {
		return go_proto_validators.FieldError("LastName", fmt.Errorf(`value '%v' must length be greater than '2'`, this.LastName))
	}
	if !(len(this.LastName) < 24) {
		return go_proto_validators.FieldError("LastName", fmt.Errorf(`value '%v' must length be less than '24'`, this.LastName))
	}
	if !(len(this.Password) > 6) {
		return go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must length be greater than '6'`, this.Password))
	}
	if !(len(this.Password) < 128) {
		return go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must length be less than '128'`, this.Password))
	}
	if !(this.RoleId > 0) {
		return go_proto_validators.FieldError("RoleId", fmt.Errorf(`value '%v' must be greater than '0'`, this.RoleId))
	}
	if !(this.RoleId < 5) {
		return go_proto_validators.FieldError("RoleId", fmt.Errorf(`value '%v' must be less than '5'`, this.RoleId))
	}
	if !(this.TenantId > 0) {
		return go_proto_validators.FieldError("TenantId", fmt.Errorf(`value '%v' must be greater than '0'`, this.TenantId))
	}
	return nil
}
func (this *Resp) Validate() error {
	if this.CreatedAt != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.CreatedAt); err != nil {
			return go_proto_validators.FieldError("CreatedAt", err)
		}
	}
	if this.UpdatedAt != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.UpdatedAt); err != nil {
			return go_proto_validators.FieldError("UpdatedAt", err)
		}
	}
	if this.DeletedAt != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.DeletedAt); err != nil {
			return go_proto_validators.FieldError("DeletedAt", err)
		}
	}
	if this.LastLogin != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.LastLogin); err != nil {
			return go_proto_validators.FieldError("LastLogin", err)
		}
	}
	if this.LastPasswordChange != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.LastPasswordChange); err != nil {
			return go_proto_validators.FieldError("LastPasswordChange", err)
		}
	}
	return nil
}
func (this *IDReq) Validate() error {
	if !(this.ID > 0) {
		return go_proto_validators.FieldError("ID", fmt.Errorf(`value '%v' must be greater than '0'`, this.ID))
	}
	return nil
}
func (this *ListResp) Validate() error {
	for _, item := range this.Users {
		if item != nil {
			if err := go_proto_validators.CallValidatorIfExists(item); err != nil {
				return go_proto_validators.FieldError("Users", err)
			}
		}
	}
	return nil
}
func (this *ListReq) Validate() error {
	if !(this.Page > 0) {
		return go_proto_validators.FieldError("Page", fmt.Errorf(`value '%v' must be greater than '0'`, this.Page))
	}
	if !(this.Limit > -1) {
		return go_proto_validators.FieldError("Limit", fmt.Errorf(`value '%v' must be greater than '-1'`, this.Limit))
	}
	return nil
}
func (this *UpdateReq) Validate() error {
	if !(this.ID > 0) {
		return go_proto_validators.FieldError("ID", fmt.Errorf(`value '%v' must be greater than '0'`, this.ID))
	}
	if !(len(this.FirstName) > 2) {
		return go_proto_validators.FieldError("FirstName", fmt.Errorf(`value '%v' must length be greater than '2'`, this.FirstName))
	}
	if !(len(this.FirstName) < 24) {
		return go_proto_validators.FieldError("FirstName", fmt.Errorf(`value '%v' must length be less than '24'`, this.FirstName))
	}
	if !(len(this.LastName) > 2) {
		return go_proto_validators.FieldError("LastName", fmt.Errorf(`value '%v' must length be greater than '2'`, this.LastName))
	}
	if !(len(this.LastName) < 24) {
		return go_proto_validators.FieldError("LastName", fmt.Errorf(`value '%v' must length be less than '24'`, this.LastName))
	}
	return nil
}
func (this *MessageResp) Validate() error {
	return nil
}
