// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rpc/iam/service.proto

/*
Package iam is a generated protocol buffer package.

It is generated from these files:
	rpc/iam/service.proto

It has these top-level messages:
	AuthReq
	AuthResp
	RefreshReq
	RefreshResp
*/
package iam

import fmt "fmt"
import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *AuthReq) Validate() error {
	if this.Auth == "" {
		return go_proto_validators.FieldError("Auth", fmt.Errorf(`value '%v' must not be an empty string`, this.Auth))
	}
	if this.Password == "" {
		return go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must not be an empty string`, this.Password))
	}
	return nil
}
func (this *AuthResp) Validate() error {
	return nil
}
func (this *RefreshReq) Validate() error {
	if !(len(this.Token) == 20) {
		return go_proto_validators.FieldError("Token", fmt.Errorf(`value '%v' must length be not equal '20'`, this.Token))
	}
	return nil
}
func (this *RefreshResp) Validate() error {
	return nil
}
